#sets up initial values of all foods
scoreboard players set @s mp.nutr.apl 25
scoreboard players set @s mp.nutr.bpt 25
scoreboard players set @s mp.nutr.brt 25
scoreboard players set @s mp.nutr.bts 25
scoreboard players set @s mp.nutr.brd 25
scoreboard players set @s mp.nutr.crt 25
scoreboard players set @s mp.nutr.chr 25
scoreboard players set @s mp.nutr.cck 25
scoreboard players set @s mp.nutr.ccd 25
scoreboard players set @s mp.nutr.cmt 25
scoreboard players set @s mp.nutr.cpc 25
scoreboard players set @s mp.nutr.crb 25
scoreboard players set @s mp.nutr.csl 25
scoreboard players set @s mp.nutr.cki 25
scoreboard players set @s mp.nutr.klp 25
scoreboard players set @s mp.nutr.eap 25
scoreboard players set @s mp.nutr.gwb 25
scoreboard players set @s mp.nutr.gap 25
scoreboard players set @s mp.nutr.gct 25
scoreboard players set @s mp.nutr.hny 25
scoreboard players set @s mp.nutr.mln 25
scoreboard players set @s mp.nutr.mrs 25
scoreboard players set @s mp.nutr.ppt 25
scoreboard players set @s mp.nutr.pto 25
scoreboard players set @s mp.nutr.pff 25
scoreboard players set @s mp.nutr.pkp 25
scoreboard players set @s mp.nutr.rbs 25
scoreboard players set @s mp.nutr.rbf 25
scoreboard players set @s mp.nutr.rck 25
scoreboard players set @s mp.nutr.rcd 25
scoreboard players set @s mp.nutr.rmt 25
scoreboard players set @s mp.nutr.rpc 25
scoreboard players set @s mp.nutr.rrb 25
scoreboard players set @s mp.nutr.rsl 25
scoreboard players set @s mp.nutr.rfl 25
scoreboard players set @s mp.nutr.eye 25
scoreboard players set @s mp.nutr.stk 25
scoreboard players set @s mp.nutr.sus 25
scoreboard players set @s mp.nutr.swb 25
scoreboard players set @s mp.nutr.tcl 25